parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  project: ['./packages/**/tsconfig.json', './tsconfig.json']
plugins:
  - "@typescript-eslint"
  - react
  - react-hooks
  - prettier
  - simple-import-sort
  - import
  - compat
  - functional
  - promise
  - sonarjs
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:import/typescript"
  - "plugin:compat/recommended"
  - "plugin:functional/external-recommended"
  - "plugin:functional/recommended"
  - "plugin:functional/stylitic"
  - "plugin:promise/recommended"
  - "plugin:sonarjs/recommended"
  - "plugin:prettier/recommended"
  - "prettier/@typescript-eslint"
  - "prettier/react"
settings:
  react:
    version: detect
  propWrapperFunctions: []
  linkComponents:
    # Components used as alternatives to <a> for linking, eg. <Link to={ url } />
    - {"name": "Link", "linkAttribute": "to"}
env:
  browser: true
rules:
  # Imports
  "simple-import-sort/imports": "error"
  "simple-import-sort/exports": "error"
  "sort-imports": "off"
  "import/first": "error"
  "import/newline-after-import": "error"
  "import/no-duplicates": "error"
