name: code

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

defaults:
  run:
    shell: bash

jobs:
  bare:
    runs-on: ubuntu-22.04
    name: ${{ matrix.operation.name }}
    timeout-minutes: 20
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        operation:
          - name: yarn install --check-cache
            command: yarn install --immutable --immutable-cache --check-cache
          - name: yarn constraints
            command: yarn constraints
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - run: ${{ matrix.operation.command }}

  with-packages:
    runs-on: ubuntu-20.04
    name: ${{ matrix.operation.name }}
    timeout-minutes: 20
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        operation:
          - name: yarn app:test
            command: yarn app:test
          - name: yarn app:eslint:check
            command: yarn app:eslint:check
          - name: yarn app:tsc:check
            command: yarn app:tsc:check
          - name: yarn prettier:check
            command: yarn prettier:check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - run: yarn install --immutable --immutable-cache
      - run: ${{ matrix.operation.command }}

  build:
    runs-on: ubuntu-20.04
    name: ${{ matrix.operation.name }}
    timeout-minutes: 20
    permissions:
      contents: read
    outputs:
      artifact: ${{ matrix.operation.artifact }}
    strategy:
      fail-fast: false
      matrix:
        operation:
          - name: yarn app:build
            command: yarn app:build
            path: packages/tt-app/build
            artifact: app.tar
          - name: yarn app:storybook:build
            command: yarn app:storybook:build
            path: packages/tt-app/storybook-static
            artifact: app-storybook.tar
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - run: yarn install --immutable --immutable-cache
      - run: ${{ matrix.operation.command }}
      - run: tar --directory "${{ matrix.operation.path }}" -cvf "${{ runner.temp }}/build.tar" "."
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.operation.artifact }}
          path: ${{ runner.temp }}/build.tar
          if-no-files-found: error
          retention-days: 5

  pages:
    name: deploy ${{ matrix.operation.name }} to pages
    needs:
      - build
    if: github.event_name != 'pull_request'
    permissions:
      pages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        operation:
          - name: app
            artifact: app.tar
            environment: github-pages
    uses: ./.github/workflows/pages.yml
    with:
      artifact: ${{ matrix.operation.artifact }}
      environment: ${{ matrix.operation.environment }}
